## static_countries
UPDATE static_countries SET cn_short_pl = 'Andora', cn_official_name_pl = 'Księstwo Andory' WHERE cn_iso_2 = 'AD';
UPDATE static_countries SET cn_short_pl = 'Zjednoczone Emiraty Arabskie' WHERE cn_iso_2 = 'AE';
UPDATE static_countries SET cn_short_pl = 'Afganistan', cn_official_name_pl = 'Islamska Republika Afganistanu' WHERE cn_iso_2 = 'AF';
UPDATE static_countries SET cn_short_pl = 'Antigua i Barbuda' WHERE cn_iso_2 = 'AG';
UPDATE static_countries SET cn_short_pl = 'Anguilla' WHERE cn_iso_2 = 'AI';
UPDATE static_countries SET cn_short_pl = 'Albania', cn_official_name_pl = 'Republika Albanii' WHERE cn_iso_2 = 'AL';
UPDATE static_countries SET cn_short_pl = 'Armenia', cn_official_name_pl = 'Republika Armenii' WHERE cn_iso_2 = 'AM';
UPDATE static_countries SET cn_short_pl = 'Antyle Holenderskie' WHERE cn_iso_2 = 'AN';
UPDATE static_countries SET cn_short_pl = 'Angola' WHERE cn_iso_2 = 'AO';
UPDATE static_countries SET cn_short_pl = 'Antarktyda' WHERE cn_iso_2 = 'AQ';
UPDATE static_countries SET cn_short_pl = 'Argentyna', cn_official_name_pl = 'Republika Argentyńska' WHERE cn_iso_2 = 'AR';
UPDATE static_countries SET cn_short_pl = 'Samoa Amerykańskie' WHERE cn_iso_2 = 'AS';
UPDATE static_countries SET cn_short_pl = 'Austria', cn_official_name_pl = 'Republika Austrii' WHERE cn_iso_2 = 'AT';
UPDATE static_countries SET cn_short_pl = 'Australia' WHERE cn_iso_2 = 'AU';
UPDATE static_countries SET cn_short_pl = 'Aruba' WHERE cn_iso_2 = 'AW';
UPDATE static_countries SET cn_short_pl = 'Azerbejdżan', cn_official_name_pl = 'Republika Azerbejdżanu' WHERE cn_iso_2 = 'AZ';
UPDATE static_countries SET cn_short_pl = 'Bośnia i Hercegowina' WHERE cn_iso_2 = 'BA';
UPDATE static_countries SET cn_short_pl = 'Barbados' WHERE cn_iso_2 = 'BB';
UPDATE static_countries SET cn_short_pl = 'Bangladesz', cn_official_name_pl = 'Ludowa Republika Bangladeszu' WHERE cn_iso_2 = 'BD';
UPDATE static_countries SET cn_short_pl = 'Belgia', cn_official_name_pl = 'Królestwo Belgii' WHERE cn_iso_2 = 'BE';
UPDATE static_countries SET cn_short_pl = 'Burkina Faso' WHERE cn_iso_2 = 'BF';
UPDATE static_countries SET cn_short_pl = 'Bułgaria', cn_official_name_pl = 'Republika Bułgarii' WHERE cn_iso_2 = 'BG';
UPDATE static_countries SET cn_short_pl = 'Bahrajn', cn_official_name_pl = 'Królestwo Bahrajnu' WHERE cn_iso_2 = 'BH';
UPDATE static_countries SET cn_short_pl = 'Burundi', cn_official_name_pl = 'Republika Burundi' WHERE cn_iso_2 = 'BI';
UPDATE static_countries SET cn_short_pl = 'Benin' WHERE cn_iso_2 = 'BJ';
UPDATE static_countries SET cn_short_pl = 'Bermudy' WHERE cn_iso_2 = 'BM';
UPDATE static_countries SET cn_short_pl = 'Brunei', cn_official_name_pl = 'Brunei Darussalam' WHERE cn_iso_2 = 'BN';
UPDATE static_countries SET cn_short_pl = 'Boliwia', cn_official_name_pl = 'Wielonarodowe Państwo Boliwia' WHERE cn_iso_2 = 'BO';
UPDATE static_countries SET cn_short_pl = 'Brazylia', cn_official_name_pl = 'Federacyjna Republika Brazylii' WHERE cn_iso_2 = 'BR';
UPDATE static_countries SET cn_short_pl = 'Bahamy' WHERE cn_iso_2 = 'BS';
UPDATE static_countries SET cn_short_pl = 'Bhutan', cn_official_name_pl = 'Wspólnota Bahamów' WHERE cn_iso_2 = 'BT';
UPDATE static_countries SET cn_short_pl = 'Wyspa Bouveta' WHERE cn_iso_2 = 'BV';
UPDATE static_countries SET cn_short_pl = 'Botswana', cn_official_name_pl = 'Republika Botswany' WHERE cn_iso_2 = 'BW';
UPDATE static_countries SET cn_short_pl = 'Białoruś', cn_official_name_pl = 'Republika Białorusi' WHERE cn_iso_2 = 'BY';
UPDATE static_countries SET cn_short_pl = 'Belize' WHERE cn_iso_2 = 'BZ';
UPDATE static_countries SET cn_short_pl = 'Kanada' WHERE cn_iso_2 = 'CA';
UPDATE static_countries SET cn_short_pl = 'Wyspa Kokosowa' WHERE cn_iso_2 = 'CC';
UPDATE static_countries SET cn_short_pl = 'Kongo', cn_official_name_pl = 'Demokratyczna Republika Kongo' WHERE cn_iso_2 = 'CD';
UPDATE static_countries SET cn_short_pl = 'Republika Środkowoafrykańska' WHERE cn_iso_2 = 'CF';
UPDATE static_countries SET cn_short_pl = 'Kongo - Brazzaville', cn_official_name_pl = 'Republika Konga' WHERE cn_iso_2 = 'CG';
UPDATE static_countries SET cn_short_pl = 'Szwajcaria', cn_official_name_pl = 'Konfederacja Szwajcarska' WHERE cn_iso_2 = 'CH';
UPDATE static_countries SET cn_short_pl = 'Wybrzeże Kości Słoniowej', cn_official_name_pl = 'Republika Wybrzeża Kości Słoniowej' WHERE cn_iso_2 = 'CI';
UPDATE static_countries SET cn_short_pl = 'Wyspy Cooka' WHERE cn_iso_2 = 'CK';
UPDATE static_countries SET cn_short_pl = 'Chile', cn_official_name_pl = 'Republika Chile' WHERE cn_iso_2 = 'CL';
UPDATE static_countries SET cn_short_pl = 'Kamerun', cn_official_name_pl = 'Republika Kamerunu' WHERE cn_iso_2 = 'CM';
UPDATE static_countries SET cn_short_pl = 'Chiny', cn_official_name_pl = 'Chińska Republika Ludowa' WHERE cn_iso_2 = 'CN';
UPDATE static_countries SET cn_short_pl = 'Kolumbia', cn_official_name_pl = 'Republika Kolumbii' WHERE cn_iso_2 = 'CO';
UPDATE static_countries SET cn_short_pl = 'Kostaryka', cn_official_name_pl = 'Republika Kostaryki' WHERE cn_iso_2 = 'CR';
UPDATE static_countries SET cn_short_pl = 'Kuba', cn_official_name_pl = 'Republika Kuby' WHERE cn_iso_2 = 'CU';
UPDATE static_countries SET cn_short_pl = 'Republika Zielonego Przylądka' WHERE cn_iso_2 = 'CV';
UPDATE static_countries SET cn_short_pl = 'Wyspa Bożego Narodzenia' WHERE cn_iso_2 = 'CX';
UPDATE static_countries SET cn_short_pl = 'Cypr', cn_official_name_pl = 'Republika Cypryjska' WHERE cn_iso_2 = 'CY';
UPDATE static_countries SET cn_short_pl = 'Czechy', cn_official_name_pl = 'Republika Czeska' WHERE cn_iso_2 = 'CZ';
UPDATE static_countries SET cn_short_pl = 'Niemcy', cn_official_name_pl = 'Republika Federalna Niemiec' WHERE cn_iso_2 = 'DE';
UPDATE static_countries SET cn_short_pl = 'Dżibuti', cn_official_name_pl = 'Republika Dżibuti' WHERE cn_iso_2 = 'DJ';
UPDATE static_countries SET cn_short_pl = 'Dania', cn_official_name_pl = 'Królestwo Danii' WHERE cn_iso_2 = 'DK';
UPDATE static_countries SET cn_short_pl = 'Dominika', cn_official_name_pl = 'Wspólnota Dominiki' WHERE cn_iso_2 = 'DM';
UPDATE static_countries SET cn_short_pl = 'Dominikana', cn_official_name_pl = 'Republika Dominikańska' WHERE cn_iso_2 = 'DO';
UPDATE static_countries SET cn_short_pl = 'Algieria', cn_official_name_pl = 'Algierska Republika Ludowo-Demokratyczna' WHERE cn_iso_2 = 'DZ';
UPDATE static_countries SET cn_short_pl = 'Ekwador', cn_official_name_pl = 'Republika Ekwadoru' WHERE cn_iso_2 = 'EC';
UPDATE static_countries SET cn_short_pl = 'Estonia', cn_official_name_pl = 'Republika Estońska' WHERE cn_iso_2 = 'EE';
UPDATE static_countries SET cn_short_pl = 'Egipt', cn_official_name_pl = 'Arabska Republika Egiptu' WHERE cn_iso_2 = 'EG';
UPDATE static_countries SET cn_short_pl = 'Sahara Zachodnia', cn_official_name_pl = 'Saharyjska Arabska Republika Demokratyczna' WHERE cn_iso_2 = 'EH';
UPDATE static_countries SET cn_short_pl = 'Erytrea' WHERE cn_iso_2 = 'ER';
UPDATE static_countries SET cn_short_pl = 'Hiszpania', cn_official_name_pl = 'Królestwo Hiszpanii' WHERE cn_iso_2 = 'ES';
UPDATE static_countries SET cn_short_pl = 'Etiopia', cn_official_name_pl = 'Federalna Demokratyczna Republika Etiopii' WHERE cn_iso_2 = 'ET';
UPDATE static_countries SET cn_short_pl = 'Finlandia', cn_official_name_pl = 'Republika Finlandii' WHERE cn_iso_2 = 'FI';
UPDATE static_countries SET cn_short_pl = 'Fidżi', cn_official_name_pl = 'Republika Wysp Fidżi' WHERE cn_iso_2 = 'FJ';
UPDATE static_countries SET cn_short_pl = 'Falklandy' WHERE cn_iso_2 = 'FK';
UPDATE static_countries SET cn_short_pl = 'Mikronezja', cn_official_name_pl = 'Sfederowane Stany Mikronezji' WHERE cn_iso_2 = 'FM';
UPDATE static_countries SET cn_short_pl = 'Wyspy Owcze' WHERE cn_iso_2 = 'FO';
UPDATE static_countries SET cn_short_pl = 'Francja', cn_official_name_pl = 'Republika Francuska' WHERE cn_iso_2 = 'FR';
UPDATE static_countries SET cn_short_pl = 'Gabon', cn_official_name_pl = 'Republika Gabońska' WHERE cn_iso_2 = 'GA';
UPDATE static_countries SET cn_short_pl = 'Wielka Brytania', cn_official_name_pl = 'Zjednoczone Królestwo Wielkiej Brytanii i Irlandii Północnej' WHERE cn_iso_2 = 'GB';
UPDATE static_countries SET cn_short_pl = 'Grenada' WHERE cn_iso_2 = 'GD';
UPDATE static_countries SET cn_short_pl = 'Gruzia', cn_official_name_pl = 'Demokratyczna Republika Gruzji' WHERE cn_iso_2 = 'GE';
UPDATE static_countries SET cn_short_pl = 'Gujana Francuska' WHERE cn_iso_2 = 'GF';
UPDATE static_countries SET cn_short_pl = 'Ghana', cn_official_name_pl = 'Republika Ghany' WHERE cn_iso_2 = 'GH';
UPDATE static_countries SET cn_short_pl = 'Gibraltar' WHERE cn_iso_2 = 'GI';
UPDATE static_countries SET cn_short_pl = 'Grenlandia' WHERE cn_iso_2 = 'GL';
UPDATE static_countries SET cn_short_pl = 'Gambia', cn_official_name_pl = 'Republika Gambii' WHERE cn_iso_2 = 'GM';
UPDATE static_countries SET cn_short_pl = 'Gwinea', cn_official_name_pl = 'Republika Gwinei' WHERE cn_iso_2 = 'GN';
UPDATE static_countries SET cn_short_pl = 'Gwadelupa', cn_official_name_pl = 'Departament Zamorski Francji' WHERE cn_iso_2 = 'GP';
UPDATE static_countries SET cn_short_pl = 'Gwinea Równikowa', cn_official_name_pl = 'Republika Gwinei Równikowej' WHERE cn_iso_2 = 'GQ';
UPDATE static_countries SET cn_short_pl = 'Grecja', cn_official_name_pl = 'Republika Grecka' WHERE cn_iso_2 = 'GR';
UPDATE static_countries SET cn_short_pl = 'Georgia Południowa i Sandwich Południowy' WHERE cn_iso_2 = 'GS';
UPDATE static_countries SET cn_short_pl = 'Gwatemala' WHERE cn_iso_2 = 'GT';
UPDATE static_countries SET cn_short_pl = 'Guam' WHERE cn_iso_2 = 'GU';
UPDATE static_countries SET cn_short_pl = 'Gwinea Bissau', cn_official_name_pl = 'Republika Gwinei Bissau' WHERE cn_iso_2 = 'GW';
UPDATE static_countries SET cn_short_pl = 'Gujana', cn_official_name_pl = 'Kooperacyjna Republika Gujany' WHERE cn_iso_2 = 'GY';
UPDATE static_countries SET cn_short_pl = 'Hongkong', cn_official_name_pl = 'Specjalny Region Administracyjny Hongkong' WHERE cn_iso_2 = 'HK';
UPDATE static_countries SET cn_short_pl = 'Honduras', cn_official_name_pl = 'Republika Hondurasu' WHERE cn_iso_2 = 'HN';
UPDATE static_countries SET cn_short_pl = 'Chorwacja', cn_official_name_pl = 'Republika Chorwacji' WHERE cn_iso_2 = 'HR';
UPDATE static_countries SET cn_short_pl = 'Haiti', cn_official_name_pl = 'Republika Haiti' WHERE cn_iso_2 = 'HT';
UPDATE static_countries SET cn_short_pl = 'Węgry', cn_official_name_pl = 'Republika Węgierska' WHERE cn_iso_2 = 'HU';
UPDATE static_countries SET cn_short_pl = 'Indonezja' WHERE cn_iso_2 = 'ID';
UPDATE static_countries SET cn_short_pl = 'Irland' WHERE cn_iso_2 = 'IE';
UPDATE static_countries SET cn_short_pl = 'Izrael' WHERE cn_iso_2 = 'IL';
UPDATE static_countries SET cn_short_pl = 'Indien', cn_official_name_pl = 'Republika Indii' WHERE cn_iso_2 = 'IN';
UPDATE static_countries SET cn_short_pl = 'Brytyjskie Terytorium Oceanu Indyjskiego' WHERE cn_iso_2 = 'IO';
UPDATE static_countries SET cn_short_pl = 'Irak', cn_official_name_pl = 'Republika Iraku' WHERE cn_iso_2 = 'IQ';
UPDATE static_countries SET cn_short_pl = 'Iran', cn_official_name_pl = 'Islamska Republika Iranu' WHERE cn_iso_2 = 'IR';
UPDATE static_countries SET cn_short_pl = 'Islandia' WHERE cn_iso_2 = 'IS';
UPDATE static_countries SET cn_short_pl = 'Włochy', cn_official_name_pl = 'Republika Włoska' WHERE cn_iso_2 = 'IT';
UPDATE static_countries SET cn_short_pl = 'Jamajka' WHERE cn_iso_2 = 'JM';
UPDATE static_countries SET cn_short_pl = 'Jordania', cn_official_name_pl = 'Jordańskie Królestwo Haszymidzkie' WHERE cn_iso_2 = 'JO';
UPDATE static_countries SET cn_short_pl = 'Japonia' WHERE cn_iso_2 = 'JP';
UPDATE static_countries SET cn_short_pl = 'Kenia', cn_official_name_pl = 'Republika Kenii' WHERE cn_iso_2 = 'KE';
UPDATE static_countries SET cn_short_pl = 'Kirgistan', cn_official_name_pl = 'Republika Kirgiska' WHERE cn_iso_2 = 'KG';
UPDATE static_countries SET cn_short_pl = 'Kambodża', cn_official_name_pl = 'Królestwo Kambodży' WHERE cn_iso_2 = 'KH';
UPDATE static_countries SET cn_short_pl = 'Kiribati', cn_official_name_pl = 'Republika Kiribati' WHERE cn_iso_2 = 'KI';
UPDATE static_countries SET cn_short_pl = 'Komory', cn_official_name_pl = 'Związek Komorów'  WHERE cn_iso_2 = 'KM';
UPDATE static_countries SET cn_short_pl = 'Saint Kitts i Nevis', cn_official_name_pl = 'Saint Kitts i Nevis' WHERE cn_iso_2 = 'KN';
UPDATE static_countries SET cn_short_pl = 'Korea Północna', cn_official_name_pl = 'Republika Ludowo-Demokratyczna' WHERE cn_iso_2 = 'KP';
UPDATE static_countries SET cn_short_pl = 'Korea Południowa', cn_official_name_pl = 'Republika Korei' WHERE cn_iso_2 = 'KR';
UPDATE static_countries SET cn_short_pl = 'Kuwejt' WHERE cn_iso_2 = 'KW';
UPDATE static_countries SET cn_short_pl = 'Kajmany' WHERE cn_iso_2 = 'KY';
UPDATE static_countries SET cn_short_pl = 'Kazachstan', cn_official_name_pl = 'Republika Kazachstanu' WHERE cn_iso_2 = 'KZ';
UPDATE static_countries SET cn_short_pl = 'Laos', cn_official_name_pl = 'Laotańska Republika Ludowo-Demokratyczna' WHERE cn_iso_2 = 'LA';
UPDATE static_countries SET cn_short_pl = 'Liban' WHERE cn_iso_2 = 'LB';
UPDATE static_countries SET cn_short_pl = 'Saint Lucia' WHERE cn_iso_2 = 'LC';
UPDATE static_countries SET cn_short_pl = 'Liechtenstein', cn_official_name_pl = 'Księstwo Liechtenstein' WHERE cn_iso_2 = 'LI';
UPDATE static_countries SET cn_short_pl = 'Sri Lanka', cn_official_name_pl = 'Demokratyczna Socjalistyczna Republika Sri Lanka' WHERE cn_iso_2 = 'LK';
UPDATE static_countries SET cn_short_pl = 'Liberia', cn_official_name_pl = 'Republika Liberii' WHERE cn_iso_2 = 'LR';
UPDATE static_countries SET cn_short_pl = 'Lesotho' WHERE cn_iso_2 = 'LS';
UPDATE static_countries SET cn_short_pl = 'Litwa', cn_official_name_pl = 'Republika Litewska' WHERE cn_iso_2 = 'LT';
UPDATE static_countries SET cn_short_pl = 'Luksemburg', cn_official_name_pl = 'Wielkie Księstwo Luksemburga' WHERE cn_iso_2 = 'LU';
UPDATE static_countries SET cn_short_pl = 'Łotwa', cn_official_name_pl = 'Republika Łotewska' WHERE cn_iso_2 = 'LV';
UPDATE static_countries SET cn_short_pl = 'Libia', cn_official_name_pl = 'Wielka Arabska Libijska Dżamahirijja Ludowo-Socjalistyczna' WHERE cn_iso_2 = 'LY';
UPDATE static_countries SET cn_short_pl = 'Marokko', cn_official_name_pl = 'Królestwo Marokańskie' WHERE cn_iso_2 = 'MA';
UPDATE static_countries SET cn_short_pl = 'Monako', cn_official_name_pl = 'Księstwo Monako' WHERE cn_iso_2 = 'MC';
UPDATE static_countries SET cn_short_pl = 'Mołdawia', cn_official_name_pl = 'Republika Mołdawii' WHERE cn_iso_2 = 'MD';
UPDATE static_countries SET cn_short_pl = 'Madagaskar', cn_official_name_pl = 'Republika Madagaskaru' WHERE cn_iso_2 = 'MG';
UPDATE static_countries SET cn_short_pl = 'Wyspy Marshalla', cn_official_name_pl = 'Republika Wysp Marshalla' WHERE cn_iso_2 = 'MH';
UPDATE static_countries SET cn_short_pl = 'Macedonia', cn_official_name_pl = 'Republika Macedonii' WHERE cn_iso_2 = 'MK';
UPDATE static_countries SET cn_short_pl = 'Mali', cn_official_name_pl = 'Republika Mali' WHERE cn_iso_2 = 'ML';
UPDATE static_countries SET cn_short_pl = 'Birma', cn_official_name_pl = 'Republika Związku Mianma' WHERE cn_iso_2 = 'MM';
UPDATE static_countries SET cn_short_pl = 'Mongolia' WHERE cn_iso_2 = 'MN';
UPDATE static_countries SET cn_short_pl = 'Makau', cn_official_name_pl = 'Specjalny Region Administracyjny Makau' WHERE cn_iso_2 = 'MO';
UPDATE static_countries SET cn_short_pl = 'Mariany Północne', cn_official_name_pl = 'Wspólnota Marianów Północnych' WHERE cn_iso_2 = 'MP';
UPDATE static_countries SET cn_short_pl = 'Martynika' WHERE cn_iso_2 = 'MQ';
UPDATE static_countries SET cn_short_pl = 'Mauretania', cn_official_name_pl = 'Islamska Republika Mauretańska' WHERE cn_iso_2 = 'MR';
UPDATE static_countries SET cn_short_pl = 'Montserrat' WHERE cn_iso_2 = 'MS';
UPDATE static_countries SET cn_short_pl = 'Malta', cn_official_name_pl = 'Republika Malty' WHERE cn_iso_2 = 'MT';
UPDATE static_countries SET cn_short_pl = 'Mauritius' WHERE cn_iso_2 = 'MU';
UPDATE static_countries SET cn_short_pl = 'Malediwy', cn_official_name_pl = 'Republika Państwa Wysp' WHERE cn_iso_2 = 'MV';
UPDATE static_countries SET cn_short_pl = 'Malawi', cn_official_name_pl = 'Republika Malawi' WHERE cn_iso_2 = 'MW';
UPDATE static_countries SET cn_short_pl = 'Meksyk', cn_official_name_pl = 'Meksykańskie Stany Zjednoczone' WHERE cn_iso_2 = 'MX';
UPDATE static_countries SET cn_short_pl = 'Malezja' WHERE cn_iso_2 = 'MY';
UPDATE static_countries SET cn_short_pl = 'Mozambik', cn_official_name_pl = 'Republika Mozambiku' WHERE cn_iso_2 = 'MZ';
UPDATE static_countries SET cn_short_pl = 'Namibia', cn_official_name_pl = 'Republika Namibii' WHERE cn_iso_2 = 'NA';
UPDATE static_countries SET cn_short_pl = 'Nowa Kaledonia' WHERE cn_iso_2 = 'NC';
UPDATE static_countries SET cn_short_pl = 'Niger', cn_official_name_pl = 'Republika Nigru' WHERE cn_iso_2 = 'NE';
UPDATE static_countries SET cn_short_pl = 'Wyspa Norfolk', cn_official_name_pl = 'Terytorium Wyspy Norfolk' WHERE cn_iso_2 = 'NF';
UPDATE static_countries SET cn_short_pl = 'Nigeria', cn_official_name_pl = 'Federalna Republika Nigerii' WHERE cn_iso_2 = 'NG';
UPDATE static_countries SET cn_short_pl = 'Nikaragua', cn_official_name_pl = 'Republika Nikaragui' WHERE cn_iso_2 = 'NI';
UPDATE static_countries SET cn_short_pl = 'Holandia', cn_official_name_pl = 'Królestwa Niderlandów' WHERE cn_iso_2 = 'NL';
UPDATE static_countries SET cn_short_pl = 'Norwegia', cn_official_name_pl = 'Królestwo Norwegii' WHERE cn_iso_2 = 'NO';
UPDATE static_countries SET cn_short_pl = 'Nepal', cn_official_name_pl = 'Federalna Demokratyczna Republika Nepalu' WHERE cn_iso_2 = 'NP';
UPDATE static_countries SET cn_short_pl = 'Nauru', cn_official_name_pl = 'Republika Nauru' WHERE cn_iso_2 = 'NR';
UPDATE static_countries SET cn_short_pl = 'Niue' WHERE cn_iso_2 = 'NU';
UPDATE static_countries SET cn_short_pl = 'Nowa Zelandia' WHERE cn_iso_2 = 'NZ';
UPDATE static_countries SET cn_short_pl = 'Oman', cn_official_name_pl = 'Sułtanat Omanu' WHERE cn_iso_2 = 'OM';
UPDATE static_countries SET cn_short_pl = 'Panama', cn_official_name_pl = 'Republika Panamy' WHERE cn_iso_2 = 'PA';
UPDATE static_countries SET cn_short_pl = 'Peru', cn_official_name_pl = 'Republika Peru' WHERE cn_iso_2 = 'PE';
UPDATE static_countries SET cn_short_pl = 'Polinezja Francuska' WHERE cn_iso_2 = 'PF';
UPDATE static_countries SET cn_short_pl = 'Papua-Nowa Gwinea', cn_official_name_pl = 'Niezależne Państwo Papui-Nowej Gwinei' WHERE cn_iso_2 = 'PG';
UPDATE static_countries SET cn_short_pl = 'Filipiny', cn_official_name_pl = 'Republika Filipin' WHERE cn_iso_2 = 'PH';
UPDATE static_countries SET cn_short_pl = 'Pakistan', cn_official_name_pl = 'Islamska Republika Pakistanu' WHERE cn_iso_2 = 'PK';
UPDATE static_countries SET cn_short_pl = 'Polska', cn_official_name_pl = 'Rzeczpospolita Polska' WHERE cn_iso_2 = 'PL';
UPDATE static_countries SET cn_short_pl = 'Saint-Pierre i Miquelon', cn_official_name_pl = 'Wspólnota Terytorialna Saint-Pierre i Miquelon' WHERE cn_iso_2 = 'PM';
UPDATE static_countries SET cn_short_pl = 'Pitcairn' WHERE cn_iso_2 = 'PN';
UPDATE static_countries SET cn_short_pl = 'Portoryko' WHERE cn_iso_2 = 'PR';
UPDATE static_countries SET cn_short_pl = 'Portugalia', cn_official_name_pl = 'Republika Portugalska' WHERE cn_iso_2 = 'PT';
UPDATE static_countries SET cn_short_pl = 'Palau', cn_official_name_pl = 'Republika Palau' WHERE cn_iso_2 = 'PW';
UPDATE static_countries SET cn_short_pl = 'Paragwaj', cn_official_name_pl = 'Republika Paragwaju' WHERE cn_iso_2 = 'PY';
UPDATE static_countries SET cn_short_pl = 'Katar' WHERE cn_iso_2 = 'QA';
UPDATE static_countries SET cn_short_pl = 'Reunion' WHERE cn_iso_2 = 'RE';
UPDATE static_countries SET cn_short_pl = 'Rumunia' WHERE cn_iso_2 = 'RO';
UPDATE static_countries SET cn_short_pl = 'Rosja', cn_official_name_pl = 'Federacja Rosyjska' WHERE cn_iso_2 = 'RU';
UPDATE static_countries SET cn_short_pl = 'Rwanda', cn_official_name_pl = 'Republika Rwandy' WHERE cn_iso_2 = 'RW';
UPDATE static_countries SET cn_short_pl = 'Arabia Saudyjska', cn_official_name_pl = 'Królestwo Arabii Saudyjskiej' WHERE cn_iso_2 = 'SA';
UPDATE static_countries SET cn_short_pl = 'Wyspy Salomona' WHERE cn_iso_2 = 'SB';
UPDATE static_countries SET cn_short_pl = 'Seszele' WHERE cn_iso_2 = 'SC';
UPDATE static_countries SET cn_short_pl = 'Sudan', cn_official_name_pl = 'Republika Sudanu' WHERE cn_iso_2 = 'SD';
UPDATE static_countries SET cn_short_pl = 'Szwecja', cn_official_name_pl = 'Królestwo Szwecji' WHERE cn_iso_2 = 'SE';
UPDATE static_countries SET cn_short_pl = 'Singapur', cn_official_name_pl = 'Republika Singapuru' WHERE cn_iso_2 = 'SG';
UPDATE static_countries SET cn_short_pl = 'Wyspa Świętej Heleny', cn_official_name_pl = 'Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tristan da Cunha' WHERE cn_iso_2 = 'SH';
UPDATE static_countries SET cn_short_pl = 'Słowenia', cn_official_name_pl = 'Republika Słowenii' WHERE cn_iso_2 = 'SI';
UPDATE static_countries SET cn_short_pl = 'Svalbard i Jan Mayen' WHERE cn_iso_2 = 'SJ';
UPDATE static_countries SET cn_short_pl = 'Słowacja', cn_official_name_pl = 'Republika Słowacka' WHERE cn_iso_2 = 'SK';
UPDATE static_countries SET cn_short_pl = 'Sierra Leone', cn_official_name_pl = 'Republika Sierra Leone' WHERE cn_iso_2 = 'SL';
UPDATE static_countries SET cn_short_pl = 'San Marino', cn_official_name_pl = 'Najjaśniejsza Republika San Marino' WHERE cn_iso_2 = 'SM';
UPDATE static_countries SET cn_short_pl = 'Senegal', cn_official_name_pl = 'Republika Senegalu' WHERE cn_iso_2 = 'SN';
UPDATE static_countries SET cn_short_pl = 'Somalia', cn_official_name_pl = 'Republika Somalijska' WHERE cn_iso_2 = 'SO';
UPDATE static_countries SET cn_short_pl = 'Surinam', cn_official_name_pl = 'Republika Surinam' WHERE cn_iso_2 = 'SR';
UPDATE static_countries SET cn_short_pl = 'Wyspy Świętego Tomasza i Książęca', cn_official_name_pl = 'Demokratyczna Republika Wysp Świętego Tomasza i Książęce' WHERE cn_iso_2 = 'ST';
UPDATE static_countries SET cn_short_pl = 'Salwador', cn_official_name_pl = 'Republika Salwadoru'  WHERE cn_iso_2 = 'SV';
UPDATE static_countries SET cn_short_pl = 'Syria', cn_official_name_pl = 'Syryjska Republika Arabska' WHERE cn_iso_2 = 'SY';
UPDATE static_countries SET cn_short_pl = 'Suazi', cn_official_name_pl = 'Królestwo Suazi' WHERE cn_iso_2 = 'SZ';
UPDATE static_countries SET cn_short_pl = 'Turks i Caicos' WHERE cn_iso_2 = 'TC';
UPDATE static_countries SET cn_short_pl = 'Czad', cn_official_name_pl = 'Republika Czadu' WHERE cn_iso_2 = 'TD';
UPDATE static_countries SET cn_short_pl = 'Francuskie Terytoria Południowe i Antarktyczne' WHERE cn_iso_2 = 'TF';
UPDATE static_countries SET cn_short_pl = 'Togo', cn_official_name_pl = 'Republika Togijska' WHERE cn_iso_2 = 'TG';
UPDATE static_countries SET cn_short_pl = 'Tajlandia', cn_official_name_pl = 'Królestwo Tajlandii' WHERE cn_iso_2 = 'TH';
UPDATE static_countries SET cn_short_pl = 'Tadżykistan', cn_official_name_pl = 'Republika Tadżykistanu' WHERE cn_iso_2 = 'TJ';
UPDATE static_countries SET cn_short_pl = 'Tokelau' WHERE cn_iso_2 = 'TK';
UPDATE static_countries SET cn_short_pl = 'Turkmenistan' WHERE cn_iso_2 = 'TM';
UPDATE static_countries SET cn_short_pl = 'Tunezja', cn_official_name_pl = 'Republika Tunezyjska' WHERE cn_iso_2 = 'TN';
UPDATE static_countries SET cn_short_pl = 'Tonga', cn_official_name_pl = 'Królestwo Tonga' WHERE cn_iso_2 = 'TO';
UPDATE static_countries SET cn_short_pl = 'Timor Wschodni', cn_official_name_pl = 'Demokratyczna Republika Timoru Wschodniego' WHERE cn_iso_2 = 'TL';
UPDATE static_countries SET cn_short_pl = 'Turcja', cn_official_name_pl = 'Republika Turcji' WHERE cn_iso_2 = 'TR';
UPDATE static_countries SET cn_short_pl = 'Trynidad i Tobago' WHERE cn_iso_2 = 'TT';
UPDATE static_countries SET cn_short_pl = 'Tuvalu' WHERE cn_iso_2 = 'TV';
UPDATE static_countries SET cn_short_pl = 'Tajwan', cn_official_name_pl = 'Republika Chińska' WHERE cn_iso_2 = 'TW';
UPDATE static_countries SET cn_short_pl = 'Tanzania', cn_official_name_pl = 'Zjednoczona Republika Tanzanii' WHERE cn_iso_2 = 'TZ';
UPDATE static_countries SET cn_short_pl = 'Ukraina' WHERE cn_iso_2 = 'UA';
UPDATE static_countries SET cn_short_pl = 'Uganda', cn_official_name_pl = 'Republika Ugandy' WHERE cn_iso_2 = 'UG';
UPDATE static_countries SET cn_short_pl = 'Dalekie Wyspy Mniejsze Stanów Zjednoczonych' WHERE cn_iso_2 = 'UM';
UPDATE static_countries SET cn_short_pl = 'Stany Zjednoczone', cn_official_name_pl = 'Stany Zjednoczone Ameryki' WHERE cn_iso_2 = 'US';
UPDATE static_countries SET cn_short_pl = 'Urugwaj', cn_official_name_pl = 'Wschodnia Republika Urugwaju' WHERE cn_iso_2 = 'UY';
UPDATE static_countries SET cn_short_pl = 'Uzbekistan', cn_official_name_pl = 'Republika Uzbekistanu' WHERE cn_iso_2 = 'UZ';
UPDATE static_countries SET cn_short_pl = 'Watykan', cn_official_name_pl = 'Państwo Miasta Watykańskiego' WHERE cn_iso_2 = 'VA';
UPDATE static_countries SET cn_short_pl = 'Saint Vincent i Grenadyny' WHERE cn_iso_2 = 'VC';
UPDATE static_countries SET cn_short_pl = 'Wenezuela', cn_official_name_pl = 'Boliwariańska Republika Wenezueli' WHERE cn_iso_2 = 'VE';
UPDATE static_countries SET cn_short_pl = 'Britische Jungferninseln' WHERE cn_iso_2 = 'VG';
UPDATE static_countries SET cn_short_pl = 'Wyspy Dziewicze Stanów Zjednoczonych' WHERE cn_iso_2 = 'VI';
UPDATE static_countries SET cn_short_pl = 'Wietnam', cn_official_name_pl = 'Socjalistyczna Republika Wietnamu' WHERE cn_iso_2 = 'VN';
UPDATE static_countries SET cn_short_pl = 'Vanuatu', cn_official_name_pl = 'Republika Vanuatu' WHERE cn_iso_2 = 'VU';
UPDATE static_countries SET cn_short_pl = 'Wallis und Futuna', cn_official_name_pl = 'Terytorium Wysp Wallis i Futuna' WHERE cn_iso_2 = 'WF';
UPDATE static_countries SET cn_short_pl = 'Samoa', cn_official_name_pl = 'Niezależne Państwo Samoa' WHERE cn_iso_2 = 'WS';
UPDATE static_countries SET cn_short_pl = 'Jemen', cn_official_name_pl = 'Republika Jemeńska' WHERE cn_iso_2 = 'YE';
UPDATE static_countries SET cn_short_pl = 'Majotta', cn_official_name_pl = 'Departament Zamorski Francji Majotta' WHERE cn_iso_2 = 'YT';
UPDATE static_countries SET cn_short_pl = 'Republika Południowej Afryki' WHERE cn_iso_2 = 'ZA';
UPDATE static_countries SET cn_short_pl = 'Zambia', cn_official_name_pl = 'Republika Zambii' WHERE cn_iso_2 = 'ZM';
UPDATE static_countries SET cn_short_pl = 'Zimbabwe', cn_official_name_pl = 'Republika Zimbabwe' WHERE cn_iso_2 = 'ZW';
UPDATE static_countries SET cn_short_pl = 'Autonomia Palestyńska', cn_official_name_pl = 'Palestyńskie Władze Narodowe' WHERE cn_iso_2 = 'PS';
UPDATE static_countries SET cn_short_pl = 'Serbien und Montenegro' WHERE cn_iso_2 = 'CS';
UPDATE static_countries SET cn_short_pl = 'Wyspy Alandzkie' WHERE cn_iso_2 = 'AX';
UPDATE static_countries SET cn_short_pl = 'Wyspy Heard i McDonalda', cn_official_name_pl = 'Terytorium Wysp Heard i McDonalda' WHERE cn_iso_2 = 'HM';
UPDATE static_countries SET cn_short_pl = 'Czarnogóra', cn_official_name_pl = 'Republika Czarnogóry' WHERE cn_iso_2 = 'ME';
UPDATE static_countries SET cn_short_pl = 'Serbia', cn_official_name_pl = 'Republika Serbii' WHERE cn_iso_2 = 'RS';
UPDATE static_countries SET cn_short_pl = 'Jersey', cn_official_name_pl = 'Baliwat Jersey' WHERE cn_iso_2 = 'JE';
UPDATE static_countries SET cn_short_pl = 'Guernsey', cn_official_name_pl = 'Baliwat Guernsey' WHERE cn_iso_2 = 'GG';
UPDATE static_countries SET cn_short_pl = 'Wyspa Man' WHERE cn_iso_2 = 'IM';
UPDATE static_countries SET cn_short_pl = 'Saint-Martin', cn_official_name_pl = 'Wspólnota Saint-Martin' WHERE cn_iso_2 = 'MF';
UPDATE static_countries SET cn_short_pl = 'Saint-Barthélemy', cn_official_name_pl = 'Wspólnota Saint-Barthélemy' WHERE cn_iso_2 = 'BL';
UPDATE static_countries SET cn_short_pl = 'Bonaire, Sint Eustatius i Saba' WHERE cn_iso_2 = 'BQ';
UPDATE static_countries SET cn_short_pl = 'Curaçao' WHERE cn_iso_2 = 'CW';
UPDATE static_countries SET cn_short_pl = 'Sint Maarten' WHERE cn_iso_2 = 'SX';
UPDATE static_countries SET cn_official_name_pl = cn_short_pl WHERE cn_official_name_pl='' OR cn_official_name_pl IS NULL;


## static_country_zones
UPDATE static_country_zones SET zn_name_pl = 'Alabama' WHERE zn_country_iso_2 = 'US' AND zn_code = 'AL';
UPDATE static_country_zones SET zn_name_pl = 'Alaska' WHERE zn_country_iso_2 = 'US' AND zn_code = 'AK';
UPDATE static_country_zones SET zn_name_pl = 'Arizona' WHERE zn_country_iso_2 = 'US' AND zn_code = 'AZ';
UPDATE static_country_zones SET zn_name_pl = 'Arkansas' WHERE zn_country_iso_2 = 'US' AND zn_code = 'AR';
UPDATE static_country_zones SET zn_name_pl = 'Kalifornien' WHERE zn_country_iso_2 = 'US' AND zn_code = 'CA';
UPDATE static_country_zones SET zn_name_pl = 'Kalifornia' WHERE zn_country_iso_2 = 'US' AND zn_code = 'CO';
UPDATE static_country_zones SET zn_name_pl = 'Connecticut' WHERE zn_country_iso_2 = 'US' AND zn_code = 'CT';
UPDATE static_country_zones SET zn_name_pl = 'Delaware' WHERE zn_country_iso_2 = 'US' AND zn_code = 'DE';
UPDATE static_country_zones SET zn_name_pl = 'Dystrykt Kolumbia' WHERE zn_country_iso_2 = 'US' AND zn_code = 'DC';
UPDATE static_country_zones SET zn_name_pl = 'Floryda' WHERE zn_country_iso_2 = 'US' AND zn_code = 'FL';
UPDATE static_country_zones SET zn_name_pl = 'Georgia' WHERE zn_country_iso_2 = 'US' AND zn_code = 'GA';
UPDATE static_country_zones SET zn_name_pl = 'Guam' WHERE zn_country_iso_2 = 'US' AND zn_code = 'GU';
UPDATE static_country_zones SET zn_name_pl = 'Hawaje' WHERE zn_country_iso_2 = 'US' AND zn_code = 'HI';
UPDATE static_country_zones SET zn_name_pl = 'Idaho' WHERE zn_country_iso_2 = 'US' AND zn_code = 'ID';
UPDATE static_country_zones SET zn_name_pl = 'Illinois' WHERE zn_country_iso_2 = 'US' AND zn_code = 'IL';
UPDATE static_country_zones SET zn_name_pl = 'Indiana' WHERE zn_country_iso_2 = 'US' AND zn_code = 'IN';
UPDATE static_country_zones SET zn_name_pl = 'Iowa' WHERE zn_country_iso_2 = 'US' AND zn_code = 'IA';
UPDATE static_country_zones SET zn_name_pl = 'Kansas' WHERE zn_country_iso_2 = 'US' AND zn_code = 'KS';
UPDATE static_country_zones SET zn_name_pl = 'Kentucky' WHERE zn_country_iso_2 = 'US' AND zn_code = 'KY';
UPDATE static_country_zones SET zn_name_pl = 'Luizjana' WHERE zn_country_iso_2 = 'US' AND zn_code = 'LA';
UPDATE static_country_zones SET zn_name_pl = 'Maine' WHERE zn_country_iso_2 = 'US' AND zn_code = 'ME';
UPDATE static_country_zones SET zn_name_pl = 'Maryland' WHERE zn_country_iso_2 = 'US' AND zn_code = 'MD';
UPDATE static_country_zones SET zn_name_pl = 'Massachusetts' WHERE zn_country_iso_2 = 'US' AND zn_code = 'MA';
UPDATE static_country_zones SET zn_name_pl = 'Michigan' WHERE zn_country_iso_2 = 'US' AND zn_code = 'MI';
UPDATE static_country_zones SET zn_name_pl = 'Minnesota' WHERE zn_country_iso_2 = 'US' AND zn_code = 'MN';
UPDATE static_country_zones SET zn_name_pl = 'Missisipi' WHERE zn_country_iso_2 = 'US' AND zn_code = 'MS';
UPDATE static_country_zones SET zn_name_pl = 'Missouri' WHERE zn_country_iso_2 = 'US' AND zn_code = 'MO';
UPDATE static_country_zones SET zn_name_pl = 'Montana' WHERE zn_country_iso_2 = 'US' AND zn_code = 'MT';
UPDATE static_country_zones SET zn_name_pl = 'Nebraska' WHERE zn_country_iso_2 = 'US' AND zn_code = 'NE';
UPDATE static_country_zones SET zn_name_pl = 'Nevada' WHERE zn_country_iso_2 = 'US' AND zn_code = 'NV';
UPDATE static_country_zones SET zn_name_pl = 'New Hampshire' WHERE zn_country_iso_2 = 'US' AND zn_code = 'NH';
UPDATE static_country_zones SET zn_name_pl = 'New Jersey' WHERE zn_country_iso_2 = 'US' AND zn_code = 'NJ';
UPDATE static_country_zones SET zn_name_pl = 'Nowy Meksyk' WHERE zn_country_iso_2 = 'US' AND zn_code = 'NM';
UPDATE static_country_zones SET zn_name_pl = 'Nowy Jork' WHERE zn_country_iso_2 = 'US' AND zn_code = 'NY';
UPDATE static_country_zones SET zn_name_pl = 'Karolina Północna' WHERE zn_country_iso_2 = 'US' AND zn_code = 'NC';
UPDATE static_country_zones SET zn_name_pl = 'Dakota Północna' WHERE zn_country_iso_2 = 'US' AND zn_code = 'ND';
UPDATE static_country_zones SET zn_name_pl = 'Ohio' WHERE zn_country_iso_2 = 'US' AND zn_code = 'OH';
UPDATE static_country_zones SET zn_name_pl = 'Oklahoma' WHERE zn_country_iso_2 = 'US' AND zn_code = 'OK';
UPDATE static_country_zones SET zn_name_pl = 'Oregon' WHERE zn_country_iso_2 = 'US' AND zn_code = 'OR';
UPDATE static_country_zones SET zn_name_pl = 'Pensylwania' WHERE zn_country_iso_2 = 'US' AND zn_code = 'PA';
UPDATE static_country_zones SET zn_name_pl = 'Portoryko' WHERE zn_country_iso_2 = 'US' AND zn_code = 'PR';
UPDATE static_country_zones SET zn_name_pl = 'Rhode Island' WHERE zn_country_iso_2 = 'US' AND zn_code = 'RI';
UPDATE static_country_zones SET zn_name_pl = 'Karolina Południowa' WHERE zn_country_iso_2 = 'US' AND zn_code = 'SC';
UPDATE static_country_zones SET zn_name_pl = 'Dakota Południowa' WHERE zn_country_iso_2 = 'US' AND zn_code = 'SD';
UPDATE static_country_zones SET zn_name_pl = 'Tennessee' WHERE zn_country_iso_2 = 'US' AND zn_code = 'TN';
UPDATE static_country_zones SET zn_name_pl = 'Teksas' WHERE zn_country_iso_2 = 'US' AND zn_code = 'TX';
UPDATE static_country_zones SET zn_name_pl = 'Utah' WHERE zn_country_iso_2 = 'US' AND zn_code = 'UT';
UPDATE static_country_zones SET zn_name_pl = 'Vermont' WHERE zn_country_iso_2 = 'US' AND zn_code = 'VT';
UPDATE static_country_zones SET zn_name_pl = 'Wirginia' WHERE zn_country_iso_2 = 'US' AND zn_code = 'VA';
UPDATE static_country_zones SET zn_name_pl = 'Waszyngton' WHERE zn_country_iso_2 = 'US' AND zn_code = 'WA';
UPDATE static_country_zones SET zn_name_pl = 'Wirginia Zachodnia' WHERE zn_country_iso_2 = 'US' AND zn_code = 'WV';
UPDATE static_country_zones SET zn_name_pl = 'Wisconsin' WHERE zn_country_iso_2 = 'US' AND zn_code = 'WI';
UPDATE static_country_zones SET zn_name_pl = 'Wyoming' WHERE zn_country_iso_2 = 'US' AND zn_code = 'WY';


## Update for data inserted previously by static_info_tables
UPDATE static_country_zones SET zn_name_pl = zn_name_local WHERE zn_country_iso_2 = 'PL'


## static_currencies
UPDATE static_currencies SET cu_name_pl = 'Dolar australijski', cu_sub_name_pl = 'cent' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_pl = 'Dolar kanadyjski', cu_sub_name_pl = 'cent' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_pl = 'Frank szwajcarski', cu_sub_name_pl = '' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_pl = 'Korona czeska', cu_sub_name_pl = 'halerz' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_pl = 'Korona duńska', cu_sub_name_pl = 'øre' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_pl = 'Euro', cu_sub_name_pl = 'cent' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_pl = 'Funt brytyjski', cu_sub_name_pl = 'pens' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_pl = 'Forint wegierski', cu_sub_name_pl = 'centym' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_pl = 'Jen japoński', cu_sub_name_pl = 'sen' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_pl = 'Lit litewski', cu_sub_name_pl = 'cent' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_pl = 'Korona norweska', cu_sub_name_pl = 'øre' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_pl = 'Złoty polski', cu_sub_name_pl = 'grosz', cu_thousands_point = ' ', cu_decimal_point = ',', cu_sub_symbol_right = 'gr' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_pl = 'Rubel rosyjski', cu_sub_name_pl = 'kopiejka' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_pl = 'Korona szwedzka', cu_sub_name_pl = 'öre' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_pl = 'Dolar amerykański', cu_sub_name_pl = 'cent' WHERE cu_iso_3='USD';


## static_languages
UPDATE static_languages SET lg_name_pl = 'abchaski' WHERE lg_iso_2 = 'AB' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'afar' WHERE lg_iso_2 = 'AA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'afrykanerski' WHERE lg_iso_2 = 'AF' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'albański' WHERE lg_iso_2 = 'SQ' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'amharski' WHERE lg_iso_2 = 'AM' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'arabski' WHERE lg_iso_2 = 'AR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ormiański' WHERE lg_iso_2 = 'HY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'assamski' WHERE lg_iso_2 = 'AS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ajmara' WHERE lg_iso_2 = 'AY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'azerski' WHERE lg_iso_2 = 'AZ' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'baszkirski' WHERE lg_iso_2 = 'BA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'baskijski' WHERE lg_iso_2 = 'EU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'bengalski' WHERE lg_iso_2 = 'BN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'dzongkha' WHERE lg_iso_2 = 'DZ' AND lg_country_iso_2 = '';
## http://en.wikipedia.org/wiki/Bihari_languages
UPDATE static_languages SET lg_name_pl = 'bihari' WHERE lg_iso_2 = 'BH' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'bislama' WHERE lg_iso_2 = 'BI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'bretoński' WHERE lg_iso_2 = 'BR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'bułgarski' WHERE lg_iso_2 = 'BG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'birmański' WHERE lg_iso_2 = 'MY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'białoruski' WHERE lg_iso_2 = 'BE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'khmerski' WHERE lg_iso_2 = 'KM' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kataloński' WHERE lg_iso_2 = 'CA' AND lg_country_iso_2 = '';
## http://pl.wikipedia.org/wiki/Zhuang
UPDATE static_languages SET lg_name_pl = 'zhuang' WHERE lg_iso_2 = 'ZA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'chiński (tracycyjny)' WHERE lg_iso_2 = 'ZH' AND lg_country_iso_2 = 'HK';
UPDATE static_languages SET lg_name_pl = 'korsykański' WHERE lg_iso_2 = 'CO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'chorwacki' WHERE lg_iso_2 = 'HR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'czeski' WHERE lg_iso_2 = 'CS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'duński' WHERE lg_iso_2 = 'DA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'holenderski' WHERE lg_iso_2 = 'NL' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'angielski' WHERE lg_iso_2 = 'EN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'esperanto' WHERE lg_iso_2 = 'EO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'estoński' WHERE lg_iso_2 = 'ET' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'farerski' WHERE lg_iso_2 = 'FO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'perski' WHERE lg_iso_2 = 'FA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'fidżyjski' WHERE lg_iso_2 = 'FJ' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'fiński' WHERE lg_iso_2 = 'FI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'francuski' WHERE lg_iso_2 = 'FR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'francuski kanadyjski' WHERE lg_iso_2 = 'FR' AND lg_country_iso_2 = 'CA';
UPDATE static_languages SET lg_name_pl = 'fryzyjski' WHERE lg_iso_2 = 'FY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'galicyjski' WHERE lg_iso_2 = 'GL' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'gaelicki szkocki' WHERE lg_iso_2 = 'GD' AND lg_country_iso_2 = '';
## http://en.wikipedia.org/wiki/Manx_language
UPDATE static_languages SET lg_name_pl = 'manks' WHERE lg_iso_2 = 'GV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'gruziński' WHERE lg_iso_2 = 'KA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'niemiecki' WHERE lg_iso_2 = 'DE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'nowogrecki' WHERE lg_iso_2 = 'EL' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'grenlandzki' WHERE lg_iso_2 = 'KL' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'guarani' WHERE lg_iso_2 = 'GN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'gudźarati' WHERE lg_iso_2 = 'GU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'hausa' WHERE lg_iso_2 = 'HA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'hebrajski' WHERE lg_iso_2 = 'HE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'hindi' WHERE lg_iso_2 = 'HI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'węgierski' WHERE lg_iso_2 = 'HU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'islandzki' WHERE lg_iso_2 = 'IS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'indonezyjski' WHERE lg_iso_2 = 'ID' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'inuktitut' WHERE lg_iso_2 = 'IU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'inupiak' WHERE lg_iso_2 = 'IK' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'irlandzki' WHERE lg_iso_2 = 'GA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'włoski' WHERE lg_iso_2 = 'IT' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'japoński' WHERE lg_iso_2 = 'JA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kannada' WHERE lg_iso_2 = 'KN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kaszmirski' WHERE lg_iso_2 = 'KS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kazachski' WHERE lg_iso_2 = 'KK' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ruanda-rundi (kinyarwanda)' WHERE lg_iso_2 = 'RW' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kirgiski' WHERE lg_iso_2 = 'KY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'rundi' WHERE lg_iso_2 = 'RN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'koreański' WHERE lg_iso_2 = 'KO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kurtyjski' WHERE lg_iso_2 = 'KU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'laotański' WHERE lg_iso_2 = 'LO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'łotewski' WHERE lg_iso_2 = 'LV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'lingala' WHERE lg_iso_2 = 'LN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'litewski' WHERE lg_iso_2 = 'LT' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'macedoński' WHERE lg_iso_2 = 'MK' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'malgaski' WHERE lg_iso_2 = 'MG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'malajski' WHERE lg_iso_2 = 'MS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'malajalam' WHERE lg_iso_2 = 'ML' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'maltański' WHERE lg_iso_2 = 'MT' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'maoryski' WHERE lg_iso_2 = 'MI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'marathi' WHERE lg_iso_2 = 'MR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'mołdawski' WHERE lg_iso_2 = 'MO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'mongolski' WHERE lg_iso_2 = 'MN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'nauruański' WHERE lg_iso_2 = 'NA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'nepalski' WHERE lg_iso_2 = 'NE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'norweski' WHERE lg_iso_2 = 'NO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'gaskoński' WHERE lg_iso_2 = 'OC' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'orija' WHERE lg_iso_2 = 'OR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'oromo' WHERE lg_iso_2 = 'OM' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'paszto' WHERE lg_iso_2 = 'PS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'polski' WHERE lg_iso_2 = 'PL' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'portugalski' WHERE lg_iso_2 = 'PT' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'pendżabski' WHERE lg_iso_2 = 'PA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'keczua' WHERE lg_iso_2 = 'QU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'romansz' WHERE lg_iso_2 = 'RM' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'rumuński' WHERE lg_iso_2 = 'RO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'rosyjski' WHERE lg_iso_2 = 'RU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tongo' WHERE lg_iso_2 = 'SM' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'sango' WHERE lg_iso_2 = 'SG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'serbski' WHERE lg_iso_2 = 'SR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'sotho' WHERE lg_iso_2 = 'ST' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'setswana' WHERE lg_iso_2 = 'TN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'shona' WHERE lg_iso_2 = 'SN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'sindhi' WHERE lg_iso_2 = 'SD' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'syngaleski' WHERE lg_iso_2 = 'SI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'suazi' WHERE lg_iso_2 = 'SS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'słowacki' WHERE lg_iso_2 = 'SK' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'słoweński' WHERE lg_iso_2 = 'SL' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'somalijski' WHERE lg_iso_2 = 'SO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'hiszpański' WHERE lg_iso_2 = 'ES' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'sundajski' WHERE lg_iso_2 = 'SU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'suahili' WHERE lg_iso_2 = 'SW' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'szwedzki' WHERE lg_iso_2 = 'SV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tagalski' WHERE lg_iso_2 = 'TL' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'filipiński' WHERE lg_iso_2 = 'TL' AND lg_country_iso_2 = 'PH';
UPDATE static_languages SET lg_name_pl = 'tadżycki' WHERE lg_iso_2 = 'TG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tamilski' WHERE lg_iso_2 = 'TA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tatarski' WHERE lg_iso_2 = 'TT' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'telugu' WHERE lg_iso_2 = 'TE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tajski' WHERE lg_iso_2 = 'TH' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tybetański' WHERE lg_iso_2 = 'BO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tigrinia' WHERE lg_iso_2 = 'TI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tonga' WHERE lg_iso_2 = 'TO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tswana' WHERE lg_iso_2 = 'TS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'turecki' WHERE lg_iso_2 = 'TR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'turkmeński' WHERE lg_iso_2 = 'TK' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'twi' WHERE lg_iso_2 = 'TW' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ujgurski' WHERE lg_iso_2 = 'UG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ukraiński' WHERE lg_iso_2 = 'UK' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'urdu' WHERE lg_iso_2 = 'UR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'uzbecki' WHERE lg_iso_2 = 'UZ' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'wietnamski' WHERE lg_iso_2 = 'VI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'walijski' WHERE lg_iso_2 = 'CY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'wolof' WHERE lg_iso_2 = 'WO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'xhosa' WHERE lg_iso_2 = 'XH' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'joruba' WHERE lg_iso_2 = 'YO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'zulu' WHERE lg_iso_2 = 'ZU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'bośniacki' WHERE lg_iso_2 = 'BS' AND lg_country_iso_2 = '';
## http://pl.wikipedia.org/wiki/Akan_%28lud%29
UPDATE static_languages SET lg_name_pl = 'akański' WHERE lg_iso_2 = 'AK' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'aragoński' WHERE lg_iso_2 = 'AN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'awarski' WHERE lg_iso_2 = 'AV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'bambara' WHERE lg_iso_2 = 'BM' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'czeczeński' WHERE lg_iso_2 = 'CE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'czarnogórski' WHERE lg_iso_2 = 'CH' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kri' WHERE lg_iso_2 = 'CR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'czuwaski' WHERE lg_iso_2 = 'CV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'malediwski' WHERE lg_iso_2 = 'DV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ewe' WHERE lg_iso_2 = 'EE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ful' WHERE lg_iso_2 = 'FF' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'hiri motu' WHERE lg_iso_2 = 'HO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'haitański' WHERE lg_iso_2 = 'HT' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'herero' WHERE lg_iso_2 = 'HZ' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'igbo' WHERE lg_iso_2 = 'IG' AND lg_country_iso_2 = '';
## http://pl.wikipedia.org/wiki/Yi
UPDATE static_languages SET lg_name_pl = 'yi' WHERE lg_iso_2 = 'II' AND lg_country_iso_2 = '';
## http://en.wikipedia.org/wiki/Kongo_language
UPDATE static_languages SET lg_name_pl = 'kongo' WHERE lg_iso_2 = 'KG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kikuju' WHERE lg_iso_2 = 'KI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kwanyama' WHERE lg_iso_2 = 'KJ' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kanuri' WHERE lg_iso_2 = 'KR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'komi' WHERE lg_iso_2 = 'KV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kornijski' WHERE lg_iso_2 = 'KW' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'luksemburski' WHERE lg_iso_2 = 'LB' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'luganda' WHERE lg_iso_2 = 'LG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'limburski' WHERE lg_iso_2 = 'LI' AND lg_country_iso_2 = '';
## http://pl.wikipedia.org/wiki/Luba_%28j%C4%99zyk%29
UPDATE static_languages SET lg_name_pl = 'luba' WHERE lg_iso_2 = 'LU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'marszalski' WHERE lg_iso_2 = 'MH' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'norweski (bokmål)' WHERE lg_iso_2 = 'NB' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ndebele północny' WHERE lg_iso_2 = 'ND' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ndonga' WHERE lg_iso_2 = 'NG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'norweski (nynorsk)' WHERE lg_iso_2 = 'NN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ndebele południowy' WHERE lg_iso_2 = 'NR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'nawaho' WHERE lg_iso_2 = 'NV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'cziczewa' WHERE lg_iso_2 = 'NY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'odżibwe' WHERE lg_iso_2 = 'OJ' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'osetyjski' WHERE lg_iso_2 = 'OS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'sardyński' WHERE lg_iso_2 = 'SC' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'północno samaryjski' WHERE lg_iso_2 = 'SE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tahitański' WHERE lg_iso_2 = 'TY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'venda' WHERE lg_iso_2 = 'VE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'waloński' WHERE lg_iso_2 = 'WA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'jawajski' WHERE lg_iso_2 = 'JV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'portugalski' WHERE lg_iso_2 = 'PT' AND lg_country_iso_2 = 'BR';
UPDATE static_languages SET lg_name_pl = 'chiński (uproszczony)' WHERE lg_iso_2 = 'ZH' AND lg_country_iso_2 = 'CN';
UPDATE static_languages SET lg_name_pl = 'interlingua' WHERE lg_iso_2 = 'IA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'interlingue' WHERE lg_iso_2 = 'IE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'łaciński' WHERE lg_iso_2 = 'LA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'sanskryt' WHERE lg_iso_2 = 'SA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'volapük' WHERE lg_iso_2 = 'VO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'jidysz' WHERE lg_iso_2 = 'YI' AND lg_country_iso_2 = '';
##http://pl.wikipedia.org/wiki/Alfabet_awestyjski
UPDATE static_languages SET lg_name_pl = 'awestyjski' WHERE lg_iso_2 = 'AE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'staro-cerkiewno-słowiański' WHERE lg_iso_2 = 'CU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ido' WHERE lg_iso_2 = 'IO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'pali' WHERE lg_iso_2 = 'PI' AND lg_country_iso_2 = '';


## static_territories
UPDATE static_territories SET tr_name_pl = 'Afryka' WHERE tr_iso_nr = '2';
UPDATE static_territories SET tr_name_pl = 'Oceania' WHERE tr_iso_nr = '9';
UPDATE static_territories SET tr_name_pl = 'Ameryki północna, środkowa i południowa' WHERE tr_iso_nr = '19';
UPDATE static_territories SET tr_name_pl = 'Azja' WHERE tr_iso_nr = '142';
UPDATE static_territories SET tr_name_pl = 'Europa' WHERE tr_iso_nr = '150';
UPDATE static_territories SET tr_name_pl = 'Azja wschodnia' WHERE tr_iso_nr = '30';
UPDATE static_territories SET tr_name_pl = 'Azja południowo-wschodnia' WHERE tr_iso_nr = '35';
UPDATE static_territories SET tr_name_pl = 'Azja środkowa' WHERE tr_iso_nr = '143';
UPDATE static_territories SET tr_name_pl = 'Azja zachodnia' WHERE tr_iso_nr = '145';
UPDATE static_territories SET tr_name_pl = 'Europa południowa' WHERE tr_iso_nr = '39';
UPDATE static_territories SET tr_name_pl = 'Europa wschodnia' WHERE tr_iso_nr = '151';
UPDATE static_territories SET tr_name_pl = 'Europa północna' WHERE tr_iso_nr = '154';
UPDATE static_territories SET tr_name_pl = 'Eueopa zachodnia' WHERE tr_iso_nr = '155';
UPDATE static_territories SET tr_name_pl = 'Ameryka południowa' WHERE tr_iso_nr = '5';
UPDATE static_territories SET tr_name_pl = 'Ameryka środkowa' WHERE tr_iso_nr = '13';
UPDATE static_territories SET tr_name_pl = 'Ameryka północna' WHERE tr_iso_nr = '21';
UPDATE static_territories SET tr_name_pl = 'Karaiby' WHERE tr_iso_nr = '29';
UPDATE static_territories SET tr_name_pl = 'Ameryka zachodnia' WHERE tr_iso_nr = '11';
UPDATE static_territories SET tr_name_pl = 'Afryka wschodnia' WHERE tr_iso_nr = '14';
UPDATE static_territories SET tr_name_pl = 'Afryka północna' WHERE tr_iso_nr = '15';
UPDATE static_territories SET tr_name_pl = 'Afryka środkowa' WHERE tr_iso_nr = '17';
UPDATE static_territories SET tr_name_pl = 'Afryka południowa' WHERE tr_iso_nr = '18';
UPDATE static_territories SET tr_name_pl = 'Australia i Nowa Zelandia' WHERE tr_iso_nr = '53';
UPDATE static_territories SET tr_name_pl = 'Melanezja' WHERE tr_iso_nr = '54';
UPDATE static_territories SET tr_name_pl = 'Mikronezja' WHERE tr_iso_nr = '57';
UPDATE static_territories SET tr_name_pl = 'Polinezia' WHERE tr_iso_nr = '61';
UPDATE static_territories SET tr_name_pl = 'Azja południowa' WHERE tr_iso_nr = '34';
