## static_territories
UPDATE static_territories SET tr_name_pl='Afryka ' WHERE tr_iso_nr='2';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='9';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='19';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_pl='Europa' WHERE tr_iso_nr='150';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='30';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='35';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='143';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='145';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='39';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='151';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='154';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='155';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='5';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='13';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='21';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='29';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='11';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='14';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='15';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='17';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='18';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='53';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_pl='Mikronezja' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_pl='Polinezja ' WHERE tr_iso_nr='61';
#UPDATE static_territories SET tr_name_pl='' WHERE tr_iso_nr='34';

## static_countries
UPDATE static_countries SET cn_short_pl='Andory' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_pl='Zjednoczone Emiraty Arabskie' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_pl='Afganistan' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_pl='Antigua i Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_pl='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_pl='Albania' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_pl='Armenia' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_pl='Antyle Holenderskie' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_pl='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_pl='Antarktyka' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_pl='Argentyna' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_pl='Samoa Amerykańskie' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_pl='Austria' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_pl='Związek Australijski' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_pl='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_pl='Azerbejdżan' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_pl='Bośnia i Hercegowina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_pl='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_pl='Bangladesz' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_pl='Belgia' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_pl='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_pl='Bulgaria' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_pl='Bahrajn' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_pl='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_pl='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_pl='Bermudy' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_pl='Brunei' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_pl='Boliwia' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_pl='Brazylia' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_pl='Bahamy' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_pl='Bhutan' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_pl='Wyspa Bouveta' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_pl='Botswana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_pl='Białoruś' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_pl='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_pl='Kanada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_pl='Wyspy Kokosowe' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_pl='DR Konga' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_pl='Republika Środkowoafrykańska' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_pl='Kongo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_pl='Szwajcaria' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_pl='Wybrzeże Kości Słoniowej' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_pl='Wyspy Cooka' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_pl='Chile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_pl='Kamerun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_pl='Republika Chińska' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_pl='Kolumbia' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_pl='Kostaryka' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_pl='Kuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_pl='Republika Zielonego Przylądka' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_pl='Wyspa Bożego Narodzenia' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_pl='Cypr' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_pl='Republika Czeska' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_pl='Niemcy' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_pl='Republika Dżibuti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_pl='Dania' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_pl='Dominika' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_pl='Dominikana' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_pl='Algieria' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_pl='Ekwador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_pl='Estonia' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_pl='Egipt' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_pl='Sahara Zachodnia' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_pl='Erytrea' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_pl='Hiszpania' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_pl='Etiopia' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_pl='Finlandia' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_pl='Fidżi' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_pl='Malwiny' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_pl='Mikronezja' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_pl='Wyspy Owcze' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_pl='Francja' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_pl='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_pl='Zjednoczone Królestwo' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_pl='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_pl='Gruzja' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_pl='Gujana Francuska' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_pl='Ghana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_pl='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_pl='Grenlandia' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_pl='Gambia' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_pl='Gwinea' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_pl='Gwadelupa' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_pl='Gwinea Równikowa' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_pl='Grecja' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_pl='Georgia Południowa i Sandwich Południowy' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_pl='Gwatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_pl='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_pl='Gwinea Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_pl='Gujana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_pl='Specjalny Region Administracyjny Hongkong' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_pl='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_pl='Chorwacja' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_pl='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_pl='Węgry' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_pl='Indonezja' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_pl='Irlandia' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_pl='Izrael' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_pl='Indie' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_pl='Brytyjskie Terytorium Oceanu Indyjskiego' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_pl='Irak' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_pl='Iran' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_pl='Islandia' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_pl='Włochy' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_pl='Jamajka' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_pl='Jordania' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_pl='Japonia' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_pl='Kenia' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_pl='Kirgistan' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_pl='Kambodża' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_pl='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_pl='Komory' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_pl='Saint Kitts i Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_pl='Korea Północna' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_pl='Republika Korei' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_pl='Kuwejt' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_pl='Kajmany' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_pl='Kazachstan' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_pl='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_pl='Liban' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_pl='Saint Lucia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_pl='Liechtenstein' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_pl='Sri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_pl='Liberia' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_pl='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_pl='Litwa' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_pl='Luksemburg' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_pl='Republika Łotewska' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_pl='Libia' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_pl='Maroko' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_pl='Monako' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_pl='Mołdawia' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_pl='Madagaskar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_pl='Republika Wysp Marshalla' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_pl='Mazedonien' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_pl='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_pl='Birma' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_pl='Mongolia' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_pl='Specjalny Region Administracyjny Makau' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_pl='Mariany Północne' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_pl='Martynika' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_pl='Mauretania' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_pl='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_pl='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_pl='Mauritius' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_pl='Malediwy' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_pl='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_pl='Meksyk' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_pl='Malezja' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_pl='Mozambik' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_pl='Namibia' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_pl='Nowa Kaledonia' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_pl='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_pl='Norfolk' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_pl='Nigeria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_pl='Nikaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_pl='Niderlandy' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_pl='Norwegia' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_pl='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_pl='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_pl='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_pl='Nowa Zelandia' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_pl='Oman' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_pl='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_pl='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_pl='Polinezja Francuska' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_pl='Papua-Nowa Gwinea' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_pl='Filipiny' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_pl='Pakistan' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_pl='Polska' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_pl='Saint-Pierre i Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_pl='Pitcairn ' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_pl='Portoryko' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_pl='Portugalia' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_pl='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_pl='Paragwaj' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_pl='Katar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_pl='Reunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_pl='Rumunia' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_pl='Rosja' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_pl='Rwanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_pl='Arabia Saudyjska' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_pl='Wyspy Salomona' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_pl='Seszele' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_pl='Sudan' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_pl='Szwecja' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_pl='Singapur' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_pl='Święta Helena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_pl='Słowenia' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_pl='Svalbard i Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_pl='Słowacja' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_pl='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_pl='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_pl='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_pl='Somalia' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_pl='Surinam' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_pl='Wyspy Świętego Tomasza i Książęca' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_pl='Salwador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_pl='Syria' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_pl='Suazi' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_pl='Wyspy Turks i Caicos' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_pl='Czad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_pl='Francuskie Terytoria Południowe i Antarktyczne' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_pl='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_pl='Tajlandia' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_pl='Tadżykistan' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_pl='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_pl='Turkmenistan' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_pl='Tunezja' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_pl='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_pl='Timor Wschodni' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_pl='Turcja' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_pl='Trynidad i Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_pl='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_pl='Tajwan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_pl='Tanzania' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_pl='Ukraina' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_pl='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_pl='Samoa Amerykańskie' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_pl='Stany Zjednoczone Ameryki' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_pl='Urugwaj' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_pl='Uzbekistan' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_pl='Państwo Watykańskie' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_pl='Saint Vincent i Grenadyny' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_pl='Wenezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_pl='Brytyjskie Wyspy Dziewicze' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_pl='Wyspy Dziewicze Stanów Zjednoczonych' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_pl='Wietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_pl='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_pl='Wallis i Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_pl='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_pl='Jemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_pl='Majotta' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_pl='Republika Południowej Afryki' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_pl='Zambia' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_pl='Zimbabwe' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_pl='Narodowa Władza Palestyńska' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_pl='Serbia i Czarnogóra' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_pl='Wyspy Alandzkie' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_pl='Wyspy Heard i McDonalda' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_pl='Czarnogóra' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_pl='Serbia' WHERE cn_iso_2='RS';